name = "leandag"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanDag"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
# Mathlib's header linter wants a mathlib-style copyright block referencing a
# LICENSE file this project does not have. The rest of the standard set is kept.
weak.linter.style.header = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.2"

[[lean_lib]]
name = "LeanDag"
