import LeanDagTest.DoS.Exposure
import LeanDag.DoS.Acceptance

/-!
# The acceptance rule on a concrete DAG

`dos-equivocation-and-growth.md` §2, D1–D4, against `Umerge` — the model from
`LeanDagTest.Exposure` in which validator 0's equivocation is exposed at the
merge.

`Umerge`'s round-2 frontier is `{9, 10, 11}`, authored by validators 1, 2 and
3: one block per author, which is the acceptance rule. Round 3's block `12`
references exactly that frontier, so this is the case D3 is about — the view
generated by what the validator accepted is the history of the block it goes on
to build, less the block itself.

The numbers are worth seeing, because they show the D2 bound is a *bound* and
not an identity: the three accepted histories overlap almost completely, so the
generated view is 11 blocks where `(3f+1) · max |H|` allows 36.
-/

open LeanDag

/-! ## The frontier is an accepted set -/

theorem umerge_accepted : Accepted Umerge {9, 10, 11} 2 where
  subset_ids := by decide
  round_eq := by decide
  inj := by decide

-- One block per author, and the authors are validators 1, 2, 3.
example : ({9, 10, 11} : Finset (Fin 13)).card = 3 := by decide
example : ({9, 10, 11} : Finset (Fin 13)).image (fun i => (Umerge.block i).creator)
    = {1, 2, 3} := by decide

/-- The frontier is smaller than the validator set, as `Accepted.card_le`
demands. -/
example : ({9, 10, 11} : Finset (Fin 13)).card ≤ Fintype.card (Fin 4) :=
  umerge_accepted.card_le

/-! ## D1 — the generated view is a view

That `View.ofAccepted` elaborates at all is the result; here is what it
contains. Each of `9`, `10`, `11` reaches the whole DAG below it, so the view
is everything except the other two round-2 blocks and the round-3 block. -/

example : (View.ofAccepted umerge_accepted).ids
    = {9, 10, 11, 6, 7, 8, 0, 1, 2, 3, 4} := by decide

example : (View.ofAccepted umerge_accepted).ids.card = 11 := by decide

-- Downward closure, which the definition supplies rather than assumes.
example : ∀ i ∈ (View.ofAccepted umerge_accepted).ids,
    ∀ j ∈ (Umerge.block i).refs, j ∈ (View.ofAccepted umerge_accepted).ids :=
  (View.ofAccepted umerge_accepted).complete

/-! ## D2 — the bridge, and how loose it is

Each accepted history holds 9 blocks, so the bound is `4 * 9 = 36` against an
actual 11. The slack is the overlap: the three round-2 blocks reference the
same round-1 blocks, so their histories coincide below the top. A bound is all
that is wanted — the theorem's job is to make view size a corollary of history
size, not to be tight. -/

example : (history Umerge 9).card = 9 := by decide
example : (history Umerge 10).card = 9 := by decide
example : (history Umerge 11).card = 9 := by decide

example : (View.ofAccepted umerge_accepted).ids.card ≤ (Fintype.card (Fin 4)) * 9 :=
  View.card_ofAccepted_le umerge_accepted (by decide)

/-! ## D3 — the sharp form

Block `12` references exactly the accepted frontier, so its history is the view
plus itself. -/

example : (Umerge.block 12).refs = {9, 10, 11} := by decide

example : history Umerge 12 = insert 12 (View.ofAccepted umerge_accepted).ids :=
  history_eq_insert_ofAccepted umerge_accepted (by decide) (by decide)

/-- `|V| + 1 = |H(b)|`, on real data: 11 and 12. -/
example : (View.ofAccepted umerge_accepted).ids.card + 1 = (history Umerge 12).card :=
  View.card_ofAccepted_add_one umerge_accepted (by decide) (by decide)

example : (history Umerge 12).card = 12 := by decide

/-! ## D4 — the view grows

Round 1's frontier for a validator that accepted `{6, 7, 8}`, and round 2's
`{9, 10, 11}` above it. Every round-2 block references all three, so the
covering hypothesis holds and the earlier view sits inside the later one. -/

theorem umerge_accepted_one : Accepted Umerge {6, 7, 8} 1 where
  subset_ids := by decide
  round_eq := by decide
  inj := by decide

example : (View.ofAccepted umerge_accepted_one).ids ⊆
    (View.ofAccepted umerge_accepted).ids :=
  View.ofAccepted_subset_of_refs umerge_accepted_one umerge_accepted
    (b := 9) (by decide) (by decide)

-- And it is a strict growth, not a technicality: three blocks are new.
example : (View.ofAccepted umerge_accepted_one).ids.card = 8 := by decide

/-! ### Retention

*Exclusion governs what you reference, not what you retain.* A validator that
also accepted validator 0's round-1 block `5` has a strictly larger view, even
though no block from the merge onward may reference `5`. Retaining it is what
keeps its view monotone. -/

theorem umerge_accepted_wide : Accepted Umerge {5, 6, 7, 8} 1 where
  subset_ids := by decide
  round_eq := by decide
  inj := by decide

example : (View.ofAccepted umerge_accepted_one).ids ⊆
    (View.ofAccepted umerge_accepted_wide).ids :=
  View.ofAccepted_mono umerge_accepted_one umerge_accepted_wide (by decide)

-- The retained block is genuinely extra, and genuinely un-referenceable.
example : (View.ofAccepted umerge_accepted_wide).ids.card = 9 := by decide
example : (5 : Fin 13) ∈ (View.ofAccepted umerge_accepted_wide).ids := by decide
example : ∀ i ∈ (Umerge.block 9).refs, (Umerge.block i).creator ≠ 0 := by decide

#print axioms umerge_accepted
